name: MacOS

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: zzvio/setup-graalvm@5.3
        with:
          graalvm: '21.3.0-dev-20210831_2241'
          java: java11

      - name: Gluon Build
        run: cd gojni; mvn gluonfx:build

      # - name: Make staging directory
      #   run: mkdir staging

      # - name: Copy GoBtc to staging
      #   run: cp -r gojni/target/gluonfx/x86_64-darwin/GoBtc staging

      # - name: Upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Package
      #     path: staging

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: |
          CGO_CFLAGS="-I${PWD}" go build -o libgobtc.dylib -buildmode=c-shared;\
          cp libgobtc.dylib ~/.java/packages/lib/

      - name: Test compiled java
        run: gojni/target/gluonfx/x86_64-darwin/GoBtc & sleep 5; kill $!

      - name: Upload 
        run: |
          export PATH=/Applications/MEGAcmd.app/Contents/MacOS:$PATH
          mega-logout
          mega-login ''$USERNAME'' ''$PASSWORD''
          mega-put -c ~/.java/packages/lib/libgobtc.dylib /go-plugins/btc/Darwin-x86_64/libgobtc.dylib
          mega-logout
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
